#!/usr/bin/expect -f
set timeout 20
spawn "./build-ca"
expect "Country Name (2 letter code) [DK]:\r"
send -- "\n"
expect "State or Province Name (full name) [Copenhagen]:\r"
send -- "\n"
expect "Country Name (2 letter code) [DK]:\r"
send -- "\n"
expect "State or Province Name (full name) [Copenhagen]:\r"
send -- "\n"
expect "Locality Name (eg, city) [Lyngby]:\r"
send -- "\n"
expect "Organization Name (eg, company) [VPN]:\r"
send -- "\n"
expect "Organizational Unit Name (eg, section) [DTU]:\r"
send -- "\n"
expect "Common Name (eg, your name or your server's hostname) [VPN CA]:\r"
send -- "\n"
expect "Name [server]:\r"
send -- "\n"
expect "Email Address [class=hljs-string]:\r"
send -- "\n"